import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is gitignored and regenerated by `next dev`/`next build`
    // (Next.js's own triple-slash reference to .next/types/routes.d.ts) — no
    // prior ticket's gate run ever started a real Next server, so this gap
    // in the ignore list went unnoticed until JOR-229's Playwright webServer
    // did.
    ignores: ['.next/**', 'node_modules/**', 'playwright-report/**', 'test-results/**', 'next-env.d.ts'],
  },
]

export default eslintConfig
